name: Metrics
on:
  # Memperbarui gambar setiap hari jam 00:00
  schedule: [{cron: "0 0 * * *"}]
  # Memungkinkan Anda menjalankan action ini secara manual
  workflow_dispatch:
  # Memperbarui gambar setiap ada push ke branch main/master
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Anda harus membuat Personal Access Token (PAT) di setting akun GitHub Anda
          # dan menyimpannya di Repository Secrets dengan nama METRICS_TOKEN
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Pengaturan agar tampilannya sama persis seperti referensi Anda
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta